version: '3.5'

services:
  mongodb:
    image: mongo:4.4.4-bionic
    container_name: booking-service-mongodb
    restart: always
    ports:
      - "27017:27017"
    command: [ --auth ]
    environment:
      ENV MONGO_INITDB_ROOT_USERNAME: admin_user
      ENV MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./config/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./local/data:/data/db

  wiremock:
    image: rodolpheche/wiremock:main
    container_name: booking-service-wiremock
    ports:
      - "10090:8080"
    volumes:
      - ./config/wiremock/__files:/home/wiremock/__files
      - ./config/wiremock/mappings:/home/wiremock/mappings

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: booking-service-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: booking-service-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
