server.port: 10088

spring:
  profiles:
    active: local
  application:
    name: booking-service
  data:
    mongodb:
      uri: mongodb://order_user:order_password@localhost:27017/order_db?authSource=admin

logging:
  config: classpath:log4j2-console.xml

integration:
  paymentService:
    baseUrl: http://localhost:10090/api