server.port: 10088

spring:
  profiles:
    active: local
  application:
    name: booking-service
  data:
    mongodb:
      uri: mongodb://order_user:order_password@localhost:27017/order_db?authSource=admin
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  config: classpath:log4j2-console.xml

integration:
  kafka:
    bootstrapAddress: http://localhost:9092
    topic: order-topic
  paymentService:
    baseUrl: http://localhost:10090/api